#ifndef LOGWITCH_PLUGINS_LOGSOURCE_LOG4CPLUS_LOG4CPLUSVERSION_H_
#define LOGWITCH_PLUGINS_LOGSOURCE_LOG4CPLUS_LOG4CPLUSVERSION_H_

#include <log4cplus/version.h>

#if LOG4CPLUS_VERSION >= 2000000
#define LOG4CPLUSV2
#endif

#endif // LOGWITCH_PLUGINS_LOGSOURCE_LOG4CPLUS_LOG4CPLUSVERSION_H_
